name: formation_dbt # nom de mon projet dbt
version: 1.0.0
profile: formation_dbt   # mon profil dbt (défini dans ~/.dbt/profiles.yml)

model-paths: ["models"] # dossier des modèles
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models: # configuration des modèles par défaut
  formation_dbt:
    taxi_trips: #nom de mon dossier de modèles
      +materialized: view # toutes les tables dans ce dossier seront des vues par défaut
